---

- name: Add new user ({{ USERNAME }}) with sudo
  user:
    name: '{{ USERNAME }}'
    password: '{{ PASSWORD_HASH }}'
    groups: sudo
    state: present
    shell: /bin/bash

- name: Configure SSH key-based authentication for created ({{ USERNAME }}) user
  authorized_key:
    user: '{{ USERNAME }}'
    state: present
    key: "{{ lookup('file', LOCAL_PUBLIC_KEY) }}"

- name: Create /etc/sudoers.d/{{ USERNAME }} for the passwordless access
  template:
    src: sudoers.j2
    dest: '/etc/sudoers.d/{{ USERNAME }}'
    owner: root
    group: root
    mode: 0440
